# Setup brew casks
cask_args appdir: '/Applications'
tap 'homebrew/cask-fonts'
tap 'homebrew/cask-versions'

brew 'mas'
brew 'asdf'
brew 'neovim'
brew 'powerlevel10k'
brew 'mpv'
brew 'tree-sitter'
brew 'autojump'

cask '1password'
cask 'iterm2'
cask 'google-chrome'
cask 'firefox'
cask 'deezer'
cask 'rancher'
cask 'signal'
cask 'whatsapp'
cask 'pocket-casts'
cask 'transmission'
cask 'visual-studio-code'
cask 'affinity-photo1' # license: https://start.1password.com/open/i?a=26FLMPKR35H7ZFPTUFFV2GEUNM&v=zumzsqvstdpy6ah235ku6t5que&i=nk2ny2ht4ph7tygzftfpcovkea&h=my.1password.com

cask 'font-caskaydia-cove-nerd-font'

mas 'PDFScanner', id: 410968114
mas '1Password for Safari', id: 1569813296
mas 'AdGuard for Safari', id: 1440147259
mas 'AusweisApp Bund', id: 948660805
